/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  interval: "5",
  options: "split",
  enabled: true,
  viewTypes: ["markdown", "canvas"]
};
var MyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.enabled = false;
    this.direction = true;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("rotate-cw", "Tab Rotation", (evt) => {
      this.enabled = !this.enabled;
      if (this.enabled) {
        this.direction = true;
        this.startTabRotation();
        new import_obsidian.Notice("Tap right rotation enabled!");
      } else {
        this.stopTabRotation();
        new import_obsidian.Notice("Tap rotation disabled!");
      }
    });
    this.addSettingTab(new SettingTab(this.app, this));
    this.addCommand({
      id: "rotate-right",
      name: "Start rotating to the right",
      callback: () => {
        if (this.enabled && !this.direction) {
          this.direction = false;
          this.stopTabRotation();
          this.startTabRotation();
          new import_obsidian.Notice("Tap right rotation enabled!");
        } else if (!this.enabled) {
          this.direction = true;
          this.startTabRotation();
          this.enabled = !this.enabled;
          new import_obsidian.Notice("Tap right rotation enabled!");
        }
      }
    });
    this.addCommand({
      id: "rotate-left",
      name: "Start rotating to the left",
      callback: () => {
        if (this.enabled && !this.direction) {
          this.direction = true;
          this.stopTabRotation();
          this.startTabRotation();
          new import_obsidian.Notice("Tap left rotation enabled!");
        } else if (!this.enabled) {
          this.direction = false;
          this.startTabRotation();
          this.enabled = !this.enabled;
          new import_obsidian.Notice("Tap left rotation enabled!");
        }
      }
    });
    this.addCommand({
      id: "stop-rotation",
      name: "Stop tab rotation",
      callback: () => {
        if (this.enabled) {
          this.stopTabRotation();
          this.enabled = !this.enabled;
          new import_obsidian.Notice("Tap rotation disabled!");
        }
      }
    });
  }
  startTabRotation() {
    if (!isNumeric(this.settings.interval)) {
      this.settings.interval = "5";
      new import_obsidian.Notice("The specified internval is not number. The default is set to 5 sec");
    } else if (parseFloat(this.settings.interval) < 0.1) {
      this.settings.interval = "5";
      new import_obsidian.Notice("The specified internval is less than 0.1 sec which is too fast. The default is set to 5 sec");
    }
    this.timerId = window.setInterval(() => {
      this.direction ? this.rotateRightTabs() : this.rotateLeftTabs();
    }, parseFloat(this.settings.interval) * 1e3);
  }
  stopTabRotation() {
    window.clearInterval(this.timerId);
  }
  getLeavesOfTypes(types) {
    const leaves = [];
    if (this.settings.options == "window") {
      this.app.workspace.iterateRootLeaves((leaf) => {
        leaves.push(leaf);
      });
    } else {
      let tabContainer = this.app.workspace.activeLeaf.parent;
      tabContainer.children.forEach((leaf) => {
        leaves.push(leaf);
      });
    }
    return leaves;
  }
  async rotateRightTabs() {
    const active = this.app.workspace.getLeaf();
    const leaves = this.getLeavesOfTypes(this.settings.viewTypes);
    if (active) {
      const index = leaves.indexOf(active);
      if (index === leaves.length - 1) {
        this.app.workspace.setActiveLeaf(leaves[0], { focus: true });
      } else {
        this.app.workspace.setActiveLeaf(leaves[index + 1], { focus: true });
      }
    }
  }
  async rotateLeftTabs() {
    const active = this.app.workspace.getLeaf();
    const leaves = this.getLeavesOfTypes(this.settings.viewTypes);
    if (active) {
      const index = leaves.indexOf(active);
      if (index === 0) {
        this.app.workspace.setActiveLeaf(leaves[leaves.length - 1], { focus: true });
      } else {
        this.app.workspace.setActiveLeaf(leaves[index - 1], { focus: true });
      }
    }
  }
  async onunload() {
    window.clearInterval(this.timerId);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Settings for Tab Rotation PlugIn" });
    new import_obsidian.Setting(containerEl).setName("Interval").setDesc("Set Interval (secs)").addText((text) => text.setPlaceholder("Enter interval (secs)").setValue(this.plugin.settings.interval).onChange(async (value) => {
      this.plugin.settings.interval = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Select rotate range").addDropdown((dropDown) => {
      dropDown.addOption("split", "Split");
      dropDown.addOption("window", "Window");
      dropDown.onChange(async (value) => {
        this.plugin.settings.options = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
function isNumeric(str) {
  if (typeof str != "string") {
    return false;
  }
  return !isNaN(Number(str)) && !isNaN(parseFloat(str));
}

/* nosourcemap */